#!/bin/sh
#
#

bind() {
    btn=$1
    cmd=$2
    shift 2
    goxhkc -button "$btn" -command "$cmd" "$@"
}

unbind() {
    btn=$1
    shift
    goxhkc -button "$btn" -clear "$@"
}

goxhkc -clearall

bind 'Mod4-v' 'notify-send "Hey"'
bind 'Mod4-v' 'notify-send "Also hey on release"' -onrelease
unbind 'Mod4-v'
unbind 'Mod4-v' -onrelease

bind 'Mod4-v' 'notify-send "Hey 123"'
bind 'Mod4-v' 'notify-send "Also Hey 123"' -onrelease

bind 'Mod4-shift-v' 'notify-send "Hello"'
bind 'Mod4-shift-v' 'notify-send "Also hello on release"' -onrelease
