#!/bin/sh
#
# A simple goxhkdrc example.

goxhkc -clearall

goxhkc -button 'Mod4-v' -command "notify-send aaa" -sh
goxhkc -button 'Mod4-v' -command "notify-send 'also aaa'" -onrelease -sh

goxhkc -button "Mod4-v" -clear

# if the command is a simple call to one program, '-sh' isn't necessary
goxhkc -button 'Mod4-v' -command "notify-send 'Actually, this'"
# otherwise it's required
goxhkc -button 'Mod4-v' -command "notify-send 'And this'; sleep 3; notify-send slep" -onrelease -sh
